# .travis.yml: Travis CI configuration
# Builds at: https://travis-ci.org/vlvrd/yocto-build

dist: trusty
sudo: required

language: python
python:
  - "2.7"

cache:
  directories:
  - external/poky/build/download
  - external/poky/build/sstate

env:
  global:
  - YOCTO_TIMEOUT=21600

before_install:
  - cd $TRAVIS_BUILD_DIR/tools/
  - sudo ./setup.sh
script:
  - cd $TRAVIS_BUILD_DIR/external/poky/
  - source oe-init-build-env
  - echo "INHERIT += ' rm_work testimage '" >> conf/local.conf
  - echo "BBLAYERS += ' $TRAVIS_BUILD_DIR/external/meta-openembedded/meta-oe $TRAVIS_BUILD_DIR/external/meta-mono '" >> conf/bblayers.conf
  - (bitbake core-image-mono) & sleep $YOCTO_TIMEOUT ; kill -INT $!

# Run tests on image
#bitbake -c testimage core-image-mono

git:
  depth: 3

#notifications:
#  email: false
